<?php

use Drupal\Core\Access\AccessResult;
use Drupal\node\NodeInterface;
use Drupal\Core\Session\AccountInterface;

/**
  * Implements hook_node_access().
  */
function hide_untranslated_node_access(NodeInterface $node, $op, AccountInterface $account) {
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if (!$node->hasTranslation($langcode)) {
    $access = AccessResult::forbidden();
  }
  else {
    $access = AccessResult::neutral();
  }
  $access->addCacheableDependency($node);
  return $access;
}
